# Generated by Django 5.0.2 on 2026-05-05 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('german', models.CharField(max_length=100, unique=True)),
                ('russian', models.CharField(max_length=200)),
                ('part_of_speech', models.CharField(blank=True, max_length=50)),
                ('example', models.TextField(blank=True)),
                ('level', models.CharField(default='A1', max_length=10)),
            ],
        ),
    ]
